name: showroom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  flutter:
    sdk: flutter
  get: 4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  json_annotation: ^4.3.0
  smooth_page_indicator: ^1.0.0+2
  geolocator: ^7.7.1
  http: ^0.13.4
  day_night_switcher: ^0.2.0+1
  
dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  lints: 1.0.1

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/flags/
  uses-material-design: true
